<H1> NUMPY INTRODUCTION </H1>

In [ ]:
#Numpy is a python library used for working with arrays, can also deal with linear algebra, fourier transform and matrices.

#reason for usage- upto 50x faster than traditional python lists

# The array object is called ndarray, also provides lots of supporting functions

In [1]:
#quickly check version

import numpy as np

print(np.__version__)

2.4.6


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#To create an ndarry, you can pass a list, tuple or any array-like object into array()

In [ ]:
# DIMENSION IN ARRAYS
#a dimension in arrays is one level of array depth (nested arrays)

In [1]:
#0-D Arrays -> or scalars. each value in an array is a 0-D array.
import numpy as np

arr = np.array(42)

print(arr)

42


In [4]:
# 1-D arrays -> an array that has 0-D arrays as its elements is called uni-dimensional or 1-D arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [6]:
# 2-D arrays -> an array that has 1-D arrays as elements

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# 3-D arrays -> an array that has 2-D arrays(matrices) as its elements

import numpy as np

arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
(2, 2, 3)


In [10]:
#higher dimensional arrays
#when array is created you can define number of dimensions by using ndmin

import numpy as np

arr = np.array([1,2,3,4], ndmin = 5)

print(arr)

print("number of dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [2]:
#Numpy array indexing
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(arr[3])
print(arr[3]+ arr[4])

4
9


In [3]:
#Access 2-D array
#negative indexing also works

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [5]:
#Numpy array slicing -> pass slice like [start:end] or [start:end:end]

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

print(arr[1:5])
print(arr[4:])


[2 3 4 5]
[5 6 7 8]


In [9]:
#Slicing 2-D arrays
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, 1:4]) #slice from the second array

print(arr[0:2, 2]) #from both arrays get the index 2 value

print(arr[0:2, 1:4]) #slice from both arrays

print(arr.dtype) #checking for data type

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
int64


In [10]:
#Converting data-type on existing Arrays

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [11]:
# Numpy Array copy vs View
# difference between copy and a view of an array-> copy is new array, view is just view of the original array

import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [12]:
#for view
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [13]:
#make a view, change a view and display both arrays

import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()

x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [1]:
#checking if array owns the data

import numpy as np
arr = np.array([1,2,3,4,5])

x = arr.copy()
y = arr.view()

print(x.base) # gives out none because has no base i.e. a true copy
print(y.base) # they give out the array



None
[1 2 3 4 5]


SHAPE OF AN ARRAY

In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr.shape) # the output (2,5) means the array has 2 dimensions, the 1st dimension has 2 elements and the second has 4

(2, 5)


In [3]:
# setting shape of an array

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [4]:
# Array reshaping-

# reshaping means changing the shape of an array, you can add or remove dimensions, or change elements in each dimension

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4, 3)

print(newarr)

# The returned array is actually a view of the original array



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# UNKNOWN DIMENSIONS -> you are allowed to have one "unknown" dimension, pass -1 as a value

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#flattening an array-> use reshape(-1) to convert multidimensional array to a 1-D array
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

newarr = arr.reshape(-1)

print(newarr)



[ 1  2  3  4  5  6  7  8  9 10]


In [1]:
#iterating numpy arrays

import numpy as np

arr = np.array([1,2,3,4,5])

for x in arr:
    print(x)

1
2
3
4
5


In [3]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

for x in arr:
    print(x)  #this prints the elements in 2-D array i.e. 2 one-D arrays

for a in arr:
    for b in a:
        print(b) #this prints individual elements

[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10


In [4]:
#iterating using nditer()

import numpy as np

arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [6]:
#iterating array with different data types

import numpy as np

arr = np.array([1,2,3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

# numpy doesnt change the datatype of the element in-place, it needs some other space to perform this action and this extra space is called buffer

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [4]:
#iterating with different step size

import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

for x in np.nditer(arr[:, ::2]):     #the first ':' selects all rows, the '::2' means -> default start, default stop, and step of 2
    print(x)

1
3
5
7
9
11


In [7]:
#Enumerated iteration using ndenumerate()

import numpy as np

arr = np.array([1,2,3])

arr2 = np.array([[1,2,3,4], [5,6,7,8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

for idx, x in np.ndenumerate(arr2):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [9]:
#Joining NumPy arrays
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [10]:
import numpy as np

arr1 = ([[1,2], [3,4]])
arr2 = ([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis = 1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
#using stack

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis =1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
#stacking along Rows
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arrh = np.hstack((arr1, arr2))
print(arrh)

#stacking along columns
arrv = np.vstack((arr1, arr2))
print(arrv)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [2]:
#stacking along Height(depth)

import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arrd = np.dstack((arr1, arr2))

print(arrd)

[[[1 4]
  [2 5]
  [3 6]]]


depth stack forces the arrays into a 3D space, i.e. it converts 1D arrays to 3D shape (1, 3, 1) before operating on them

In [4]:
#SPLITTING NUMPY ARRAYS

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [6]:
#splitting into more parts

import numpy as np
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr, 4)
print(newarr)

#you can also use indexing on the newarr to get individual arrays

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [8]:
#splitting 2-D arrays
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [9]:
#splitting along columns

import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18]])

newarr = np.array_split(arr, 3, axis =1)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [10]:
#searching arrays -> use np.where
arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [2]:
#Search sorted, performs binary search in an array, and returns the index where te specified value would be inserted to maintain search order

#it is assumed to be used on sorted arrays
import numpy as np

arr = np.array([6,7,8,9])
x = np.searchsorted(arr, 7)
print(x)

#you can also select side for index
y = np.searchsorted(arr, 7, side='right')
print(y)


1
2


In [5]:
#Sorting arrays
import numpy as np

arr= np.array([3,6,2,7,8,3])
print(np.sort(arr))  #this method returns a copy of the array, original array unchanged

[2 3 3 6 7 8]


In [6]:
#alphabetical and boolean arrays can also be sorted

# when you try to sort a 2-D array, individual arrays will be sorted

import numpy as np

arr = np.array([[2,4,1], [6,2,9]])
print(np.sort(arr))

[[1 2 4]
 [2 6 9]]


In [1]:
#filtering arrays -> filtering means sorting elements out of existing array and create a new array
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [2]:
#more practical example
import numpy as np

arr = np.array([41,42,43,44])

#create an empty list
filter_arr =[]

#going through entire array
for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(newarr)

[43 44]


In [5]:
#Creating filter Directly from array
import numpy as np

arr = np.array([41,42,43,44])

filter_arr = arr > 42
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [20]:
#RANDOM NUMBER

from numpy import random

x = random.randint(100)
print(x)

y = random.rand()
print(y)



28
0.09798770467013607


In [2]:
#generate random array -> 1D array
from numpy import random

x = random.randint(100, size=(5))

print(x)

#generate random 2D array
y = random.randint(100, size=(3,5))
print(y)

[72 70 49 83 95]
[[27 48  2 69 36]
 [86 16 24  2 86]
 [74 97 77 23 77]]


In [4]:
y = random.rand(3,6)
print(y)

[[0.6635824  0.01029854 0.25990208 0.87111996 0.11372645 0.26295282]
 [0.76249718 0.47088422 0.82340977 0.34404882 0.67593422 0.26710352]
 [0.33490083 0.85327615 0.3036104  0.74378382 0.24537824 0.54683258]]


In [12]:
#choice() allows you to generate a random value based on an array of values
from numpy import random

x = random.choice([3,5,7,9])

print(x)

5


In [2]:
import numpy as np

print(0.1 + 0.2 == 0.3)          # Output: False
print(np.isclose(0.1 + 0.2, 0.3)) # Output: True
print(0.1 + 0.2)

False
True
0.30000000000000004


In [ ]:
#random data distribution
# -> data distribution == list of all possible values and how often they occur

#random distribution -> set of random numbers that follow a certain probability density function
#probability density function -> a func. that describes a continuous probability


In [4]:
#Example
# -> generate a 1-D array containing 100 values, where each value has to be 3,5,7,9 and probabilities given for all values

from numpy import random

x = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0], size =(5,10))
print(x)

[[7 7 7 7 7 5 5 7 5 3]
 [7 5 7 5 5 3 7 7 7 7]
 [7 7 5 3 3 3 7 7 7 5]
 [7 5 5 5 7 7 7 7 7 5]
 [7 7 7 5 7 7 7 7 7 7]]


In [7]:
#random permutation of elements -> shuffle() and permutation() used
from numpy import random

import numpy as np
arr = np.array([1,2,3,4,5])
random.shuffle(arr)  #shuffle modifies existing array
print(arr)

random.permutation(arr)  #leaves original array untouched
print(arr)



[2 4 1 3 5]
[2 4 1 3 5]


In [ ]:
rgrhdrthd    g  r gerrr  gerg e t